version: '3.3'
services:
  db:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_DATABASE: millwheat
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./storage/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
